#!/bin/bash

################################################################################
# This script adds additional sample data to the SMART COSMOS Devkit
#
# To achieve this, following steps will be done:
# 1. Request a new JWT token for the given user and password
# 2. Import Things, Metadata and Relationships (as defined in *bulkimport.json*)
#
# Usage: ./addSampleData <username> <password>
################################################################################

set -e

function jsonGetValue() {
    local readonly json=$1
    local readonly key=$2
    local readonly pythonScript="import json,sys; res=json.load(sys.stdin); print res['${key}']"

    echo $(echo ${json} | python -c "${pythonScript}")
}

function jsonGetSubValue() {
    local readonly json=$1
    local readonly key=$2
    local readonly subkey=$3
    local readonly pythonScript="import json,sys; res=json.load(sys.stdin); print res['${key}']['${subkey}']"

    echo $(echo ${json} | python -c "${pythonScript}")
}

# define the SMART COSMOS DevKit instance
devkitHost="http://localhost:8080"

# define the client credentials for OAuth
clientKey="smartcosmosservice"
clientSecret="9HhnNDhfGEXfNEn6"

tenantUsername=$1
tenantPassword=$2

echo " === User Credentials === "
echo "Username: ${tenantUsername}"
echo "Password: ${tenantPassword}"

# acquire authentication token
respToken=$(curl -sS -X POST -H "Content-Type: application/json" --basic -u ${clientKey}:${clientSecret} "${devkitHost}/oauth/token?grant_type=password&scope=read&username=${tenantUsername}&password=${tenantPassword}")
token=$(jsonGetValue ${respToken} "access_token")

# output JWT token (uncomment the next 2 lines to output the JWT token for debugging)
#echo " === JWT Token === "
#echo ${token}

# send bulk import
respImport=$(curl -sS -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${token}" -d "$(cat bulkimport.json)" "${devkitHost}/bulkimport/")

echo " === Import result === "
echo ${respImport}


