= Tutorial for Importing Sample Data


This guide helps you initially populate your database by importing
sample data into the SMART COSMOS DevKit, using the **Bulk Import**
service.

This data is required for minimum functionality:

.Data types
|===
| Type | Description

| Tenant | A tenant represents an account or organization which holds all data belonging to it
| User | A user is associated with credentials which are used to log in to a
          tenant. The initial user is created automatically when the tenant
          is created.
| Thing | Things represent core entities (a car, a person, an RFID tag, ...).
| Metadata | Metadata represents properties of these Things (the car is blue).
| Relationship | Relationships represent relations between Things (this car belongs to Bob)
|===

:numbered:
== Create a Tenant

To create the new tenant, the *name* of the organization and the *username* of the initial user shall be given:

[source, bash]
----
$ curl -X POST "http://localhost:8080/tenants" \
       -H "Content-Type: application/json" \
       -d '{"name": "Example Company", "username": "waldo@example.com"}'
----

The response contains the URN of the new tenant, and the user name and password
of the initial user, who automatically has the Admin role.

[source, json]
----
{
  "urn": "urn:tenant:uuid:ff002e1e-31c7-4153-a322-d024eb991748",
  "admin": {
    "urn": "urn:user:uuid:2e094c7c-52fe-4dbb-8954-2625171520f8",
    "username": "waldo@example.com",
    "password": "lajNVdjZtCEb",
    "roles": ["Admin"],
    "tenantUrn": "urn:user:uuid:ff002e1e-31c7-4153-a322-d024eb991748"
  }
}
----

The password needs to be stored in a safe location, because it
is required for further operations on this tenant, e.g., creating
additional users, or adding data.

== Acquire an Access Token

The user requests an OAuth 2.0 access token with the known `username`/`password`
credentials returned at user (or tenant) creation.
The access token is then used for all subsequent REST API calls.

Execute the following to acquire a token for your newly created user
(remember to set the correct password):

[source, bash]
----
$ export password='lajNVdjZtCEb'
$ curl -X POST "http://localhost:8080/oauth/token?grant_type=password&scope=read&username=waldo@example.com&password=${password}" \
       -H "Content-Type: application/json" \
       --basic -u "smartcosmosservice:9HhnNDhfGEXfNEn6"
----

The response contains the OAuth 2.0 token in `access_token`.

== Construct the Bulk Import Request

The bulk import request contains a JSON body composed of two sections:

.Bulk Import Components
|===
| Name | Description

| `things` | JSON array containing Things with Metadata
| `relationships` | JSON array containing Relationships between the
                    Things defined above
|===


=== Example

We have a person and a car, where the person owns that car. The person and the car both have metadata properties:

[source, text]
----
[Thing] Person -> [Metadata] {"name": "John"}
 |
 |
[Relationship] "owns"
 |
 v
[Thing] Vehicle -> [Metadata] {"manufacturer": "Toyota", "model": "pickup truck"}
----

To import this sample data structure, create a
JSON import file that looks like the JSON below,
and name it `bulkimport.json`.

[source, json]
----
{
  "things": [
    {
      "type": "Person",
      "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000001",
      "name": "John"
    },
    {
      "type": "Vehicle",
      "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000004",
      "manufacturer": "Toyota",
      "model": "Pickup Truck"
    }
  ],
  "relationships": [
    {
      "source": {
        "type": "Person",
        "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000001"
      },
      "target": {
        "type": "Vehicle",
        "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000004"
      },
      "relationshipType": "owns"
    }
  ]
}
----

Use the `curl` command to import the data into the DevKit
(remember to set the correct access token):

[source, bash]
----
$ export token="eyJhbGci..."
$ curl -X POST "http://localhost:8080/bulkimport/" \
       -H "Content-Type: application/json" \
       -H "Authorization: Bearer ${token}" \
       -d @bulkimport.json
----

== Files in this Tutorial

.Bulk Import Components
|===
| File Name | Description

| `*`README.adoc`*` | this file
| `*`createSampleData`*` | bash script to create a new tenant and populate it with data
| `*`addSampleData`*` | bash script to log in into an existing tenant and add more data
| `*`createTenant.json`*` | example JSON which defines the new tenant
| `*`bulkimport.json`*` | example JSON which defines new Things, Metadata and Relationships to import
|===

== Tips and Tricks

The script *createSampleData* outputs the username and password of the newly created tenant. Store these credentials in a safe location. When the import fails or more data needs to be imported, run following command with the given credentials:
[source,bash]
----
$ ./addSampleData <username> <password>
----
So it is not neccessary to create a new tenant in the case the createSampleData command fails after creating the tenant.

For the bulk import the Thing urns need to be generated as unique values. When the import fails, this might be caused by already existing urns in a different tenant.
