---
version: '2'

services:
  config-server:
    image: smartcosmos/config-server
    environment:
      CONFIG_FILE_URI: 'https://github.com/SMARTRACTECHNOLOGY/smartcosmos-cluster-config'
      CONFIG_SERVER_LABEL: devkit
      ENCRYPT_KEY: 'RD@BIv2AhuFIAmKo'

  service-discovery:
    image: smartcosmos/service-discovery
    ports:
      - "8080:8080"
    depends_on:
      - config-server


  gateway:
    image: smartcosmos/gateway
    ports:
      - "8765:8080"
    depends_on:
      - config-server
      - service-discovery


  auth-server:
    image: smartcosmos/auth-server
    # make auth-server public this is needed to get a tocken directly
    # until we fix gateway --> auth-server comunication.
    ports:
      - "9999:8080"
    depends_on:
      - config-server
      - service-discovery
      - edge-user-devkit


  edge-user-devkit:
    image: smartcosmos/edge-user-devkit
    depends_on:
      - config-server
      - service-discovery
      - mysql


  edge-things:
    image: smartcosmos/edge-things
    depends_on:
      - config-server
      - service-discovery
      - ext-things
      - ext-metadata

  ext-things:
    image: smartcosmos/ext-things
    depends_on:
      - config-server
      - service-discovery
      - mysql


  ext-metadata:
    image: smartcosmos/ext-metadata
    depends_on:
      - config-server
      - service-discovery
      - mysql


  ext-relationships:
    image: smartcosmos/ext-relationships
    depends_on:
      - config-server
      - service-discovery
      - mysql


  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devkit
      MYSQL_USER: cosmos
      MYSQL_PASSWORD: dev


