---
version: '2'

services:
  config-server:
    image: smartcosmos/config-server
    ports:
      - "8888:8888"
    environment:
      CONFIG_FILE_URI: 'https://github.com/SMARTRACTECHNOLOGY/smartcosmos-cluster-config'
      CONFIG_SERVER_LABEL: devkit
      ENCRYPT_KEY: 'RD@BIv2AhuFIAmKo'

  service-discovery:
    image: smartcosmos/service-discovery
    ports:
      - "8761:8080"
    depends_on:
      - config-server

  mysql-auth:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  user-details-service:
    image: smartcosmos/user-details-service
    ports:
      - "42000:8080"
    depends_on:
      - config-server
      - mysql
    links:
     - mysql:mysql

  auth-server:
    image: smartcosmos/auth-server
    ports:
      - "9999:8080"
    depends_on:
      - config-server

  gateway:
    image: smartcosmos/gateway
    ports:
      - "8765:8080"
    depends_on:
      - config-server

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devkit
      MYSQL_USER: cosmos
      MYSQL_PASSWORD: dev

  ext-things:
    image: smartcosmos/ext-things
    ports:
      - "45336:8080"
    depends_on:
      - config-server
      - mysql
    links:
      - mysql:mysql

  ext-metadata:
    image: smartcosmos/ext-metadata
    ports:
      - "45337:8080"
    depends_on:
      - config-server
      - mysql
    links:
      - mysql:mysql
