---
version: '3'

services:
  config-server:
    image: smartcosmos/config-server
    environment:
      SPRING_PROFILES: native
      CONFIG_SEARCH_LOCATIONS: file:/opt/smartcosmos/config
      ENCRYPT_KEY: 'RD@BIv2AhuFIAmKo'
    ports:
      - "8888:8888"
    networks:
      - platform-services
    volumes:
      - ./config:/opt/smartcosmos/config

  gateway:
    image: smartcosmos/gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    networks:
      - devkit-gateway
      - platform-services

  auth-server:
    image: smartcosmos/auth-server
    environment:
      SERVER_PORT: 9999
    ports:
      - "9999:9999"
    depends_on:
      - config-server
    networks:
      - platform-services
    volumes:
      - ./config:/opt/smartcosmos/config

  edge-user-devkit:
    image: smartcosmos/edge-user-devkit
    environment:
      SERVER_PORT: 45371
    ports:
      - "45371:45371"
    depends_on:
      - config-server
      - mysql
    networks:
      - platform-services

  user-details-devkit:
    image: smartcosmos/user-details-devkit
    environment:
      SERVER_PORT: 7777
    ports:
      - "7777:7777"
    depends_on:
      - config-server
      - mysql
    networks:
      - platform-services
    restart: always

  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - platform-services

  kafka:
    image: ches/kafka
    mem_limit: 300M
    ports:
     - "9092:9092"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    depends_on:
     - zookeeper
    networks:
      - platform-services

  events:
    image: smartcosmos/events
    environment:
      SERVER_PORT: 45012
    ports:
      - "45012:45012"
    depends_on:
     - config-server
     - kafka
    networks:
      - platform-services

  edge-bulkimport:
    image: smartcosmos/edge-bulkimport
    environment:
      SERVER_PORT: 50593
    ports:
      - "50593:50593"
    depends_on:
      - config-server
    networks:
      - platform-services

  edge-things:
    image: smartcosmos/edge-things
    environment:
      SERVER_PORT: 50594
    ports:
      - "50594:50594"
    depends_on:
      - config-server
    networks:
      - platform-services

  ext-things:
    image: smartcosmos/ext-things
    environment:
      SERVER_PORT: 45336
    ports:
      - "45336:45336"
    depends_on:
      - config-server
      - mysql
    networks:
      - platform-services

  ext-metadata:
    image: smartcosmos/ext-metadata
    environment:
      SERVER_PORT: 45037
    ports:
      - "45037:45037"
    depends_on:
      - config-server
      - mysql
    networks:
      - platform-services

  ext-relationships:
    image: smartcosmos/ext-relationships
    environment:
      SERVER_PORT: 45369
    ports:
      - "45369:45369"
    depends_on:
      - config-server
      - mysql
    networks:
      - platform-services

  ext-interactions:
    image: smartcosmos/ext-interactions
    environment:
      SERVER_PORT: 45556
    ports:
      - "45556:45556"
    depends_on:
      - config-server
      - kafka
    networks:
      - platform-services

  mysql:
    image: mariadb:10.1.17
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devkit
      MYSQL_USER: cosmos
      MYSQL_PASSWORD: dev
    networks:
       - platform-services

  landing-page:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - platform-services
    volumes:
      - ./html:/usr/share/nginx/html:ro

networks:
  devkit-gateway:
    driver: bridge
  platform-services:
    driver: bridge
