---
version: '2'

services:
  config-server:
    image: smartcosmos/config-server
    ports:
      - "8888:8888"
    environment:
      CONFIG_FILE_URI: 'https://github.com/SMARTRACTECHNOLOGY/smartcosmos-cluster-config'
      CONFIG_SERVER_LABEL: devkit
      ENCRYPT_KEY: 'RD@BIv2AhuFIAmKo'

  service-discovery:
    image: smartcosmos/service-discovery
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  edge-user-devkit:
    image: smartcosmos/edge-user-devkit
    ports:
      - "42000:42000"
    depends_on:
      - config-server
      - service-discovery
      - mysql
    links:
     - mysql:mysql

  auth-server:
    image: smartcosmos/auth-server
    ports:
      - "9999:9999"
    depends_on:
      - config-server
      - edge-user-devkit
      - service-discovery

  gateway:
    image: smartcosmos/gateway
    ports:
      - "8765:8080"
    depends_on:
      - config-server
      - service-discovery

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devkit
      MYSQL_USER: cosmos
      MYSQL_PASSWORD: dev

  edge-things:
    image: smartcosmos/edge-things
    depends_on:
      - config-server
      - service-discovery
      - mysql

  ext-things:
    image: smartcosmos/ext-things
    depends_on:
      - config-server
      - service-discovery
      - mysql
    links:
      - mysql:mysql

  ext-metadata:
    image: smartcosmos/ext-metadata
    depends_on:
      - config-server
      - service-discovery
      - mysql
    links:
      - mysql:mysql

  ext-relationships:
    image: smartcosmos/ext-relationships
    depends_on:
      - config-server
      - service-discovery
      - mysql
    links:
      - mysql:mysql

  zookeeper:
    image: jplock/zookeeper:3.4.6

  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper

  events:
    image: smartcosmos/events
    depends_on:
      - config-server
      - service-discovery
      - kafka
    links:
      - kafka:kafka

  event-listener:
    image: smartcosmos/event-listener
    depends_on:
      - config-server
      - service-discovery
      - kafka
    links:
      - kafka:kafka
