---
version: '2'

services:
  config_server:
    build: smartcosmos-config-server
    image: smartcosmos/config-server
    container_name: config_server
    network_mode: host
    ports:
      - "8888:8888"
    # volumes:
    #   - "${HOME}/workspace/smartcosmos-cluster-config:/cluster-config"
    environment:
      # CONFIG_FILE_URI: 'file:cluster-config'
      CONFIG_FILE_URI: 'https://github.com/SMARTRACTECHNOLOGY/smartcosmos-cluster-config'
      ENCRYPT_KEY: 'RD@BIv2AhuFIAmKo'
  #
  # service_discovery:
  #   build: smartcosmos-service-discovery
  #   image: smartcosmos/service_discovery
  #   container_name: service_discovery
  #   network_mode: host
  #   ports:
  #     - "8761:8761"
  #   depends_on:
  #     - config_server
  #
  # user_details_service:
  #   build: smartcosmos-user-details-service
  #   image: smartcosmos/user-details-service
  #   container_name: user_details_service
  #   network_mode: host
  #   ports:
  #     - "42000:42000"
  #   depends_on:
  #     - config_server

  # auth_server:
  #   build: smartcosmos-auth-server
  #   image: smartcosmos/auth-server
  #   ports:
  #     - "9999:9999"
  #   depends_on:
  #     - config_server
