---
version: '2'

services:
  config-server:
    image: smartcosmos/config-server
    environment:
      CONFIG_FILE_URI: 'file:///opt/config'
      CONFIG_SERVER_LABEL: devkit
      ENCRYPT_KEY: 'RD@BIv2AhuFIAmKo'
    ports:
      - "8888:8888"
    volumes:
      - ~/git/smartcosmos-cluster-config:/opt/config
  service-discovery:
    image: smartcosmos/service-discovery
    depends_on:
      - config-server


  gateway:
    image: smartcosmos/gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - service-discovery


  auth-server:
    image: smartcosmos/auth-server
    # make auth-server public this is needed to get a tocken directly
    # until we fix gateway --> auth-server comunication.
    ports:
      - "9999:8080"
    depends_on:
      - config-server
      - service-discovery
      - user-details-devkit
      - edge-user-devkit


  edge-user-devkit:
    image: smartcosmos/edge-user-devkit
    depends_on:
      - config-server
      - service-discovery
      - mysql

  user-details-devkit:
    image: smartcosmos/user-details-devkit
    depends_on:
      - config-server
      - service-discovery
      - mysql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
     - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      HOSTNAME_COMMAND: "route -n | grep 'UG[ \t]' | awk '{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
     - zookeeper

  events:
    image: smartcosmos/events
    ports:
      - "45012:8080"
    depends_on:
     - config-server
     - service-discovery
     - kafka

  event-listener:
    image: smartcosmos/event-listener
    depends_on:
     - events

  edge-things:
    image: smartcosmos/edge-things
    depends_on:
      - config-server
      - service-discovery
      - auth-server
      - ext-things
      - ext-metadata

  ext-things:
    image: smartcosmos/ext-things
    depends_on:
      - config-server
      - service-discovery
      - mysql


  ext-metadata:
    image: smartcosmos/ext-metadata
    depends_on:
      - config-server
      - service-discovery
      - mysql


  ext-relationships:
    image: smartcosmos/ext-relationships
    depends_on:
      - config-server
      - service-discovery
      - mysql


  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devkit
      MYSQL_USER: cosmos
      MYSQL_PASSWORD: dev
