---
version: '2'

services:
  config-server:
    image: smartcosmos/config-server
    environment:
      CONFIG_FILE_URI: 'file:/etc/config-server'
      CONFIG_SERVER_LABEL: devkit
      ENCRYPT_KEY: 'RD@BIv2AhuFIAmKo'
    volumes:
      - '/Users/sdomula/workspace/smartcosmos-cluster-config:/etc/config-server'

  service-discovery:
    image: smartcosmos/service-discovery
    ports:
      - "8080:8080"
    depends_on:
      - config-server

  edge-user-devkit:
    image: smartcosmos/edge-user-devkit
    depends_on:
      - config-server
      - mysql

  auth-server:
    image: smartcosmos/auth-server
    ports:
      - "9999:8080"
    depends_on:
      - config-server
    
  gateway:
    image: smartcosmos/gateway
    ports:
      - "8765:8080"
    depends_on:
      - config-server

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devkit
      MYSQL_USER: cosmos
      MYSQL_PASSWORD: dev

  ext-things:
    image: smartcosmos/ext-things
    depends_on:
      - config-server
      - mysql

  ext-metadata:
    image: smartcosmos/ext-metadata
    depends_on:
      - config-server
      - mysql

  ext-relationships:
    image: smartcosmos/ext-relationships
    depends_on:
      - config-server
      - mysql
