
= SMART COSMOS Getting Started Guide
SMARTRAC Technology Fletcher Inc <api@smartrac-group.com>

== Welcome to SMART COSMOS
Welcome to SMART COSMOS!

Are you ready to become part of creating something really big? With SMART COSMOS
you can connect a universe of everyday things to the digital world. In fact,
SMART COSMOS is the only platform that is purely focused on providing a fast
track for both enterprises and developers to Monetize the IoT.

SMART COSMOS is an ecosystem. It consists of a robust partner network where
hardware manufacturers, system integrators, software developers and enterprises
come together to create the IoT. It is comprised of both SaaS and PaaS offerings
that help you EMBED, ENABLE, and UTILIZE IoT driven data.

In order to accelerate value creation with the IoT, enterprises must learn how
to obtain new value from four key areas:

* Data
* Things
* People
* Process

The IoT is nothing more than combining a creative mixture of low-cost sensing
hardware, auto-identification technologies like RFID, and the Cloud! Now, we
invite you to take the next steps and learn how to use our IoT blueprint.

Platforms are living designs that are always evolving. If you have
feedback, feature requests, or just want to meet for some drinks and talk
software design patterns, contact us either at the developer portal or via
email: mailto:api@smartrac-group.com[api@smartrac-group.com]

== Open Source Framework
SMART COSMOS includes a number of open sourced frameworks available under the
Apache License, Version 2. You can clone and freely use these frameworks in your
projects, submit pull requests, and access the latest documentation at GitHub:

 * https://github.com/SMARTRACTECHNOLOGY/smartcosmos-framework

 * https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit
(where this document was downloaded from)

IMPORTANT: The core of the Objects server itself is presently proprietary and must
be properly licensed when deployed in a production environment.

In addition to the open source development framework, the entirety of the
SMART COSMOS Objects REST Web Service APIs are fully documented at our https://api.smartcosmos.net[API Documentation web page] and the https://documenter.getpostman.com/view/437937/smart-cosmos-objects-devkit-api-tutorial/2JvFAy[SMART COSMOS Objects DevKit API Tutorial].


[width="100%",options="header,footer"]
|==================== 
|Service|API links|Configuration|Description
|Authentication Server|https://api.smartcosmos.net/microservices/smartcosmos-auth-server/index.html[API]|https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-auth-server.yml[smartcosmos-auth-server.yml]|
|User Management DevKit|https://api.smartcosmos.net/microservices/smartcosmos-edge-user-devkit/index.html[API]|https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-edge-user-devkit.yml[smartcosmos-edge-user-devkit.yml]|
|Things|https://api.smartcosmos.net/microservices/smartcosmos-edge-things/index.html[API]|https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-edge-things.yml[smartcosmos-edge-things.yml]|
|Relationships|https://api.smartcosmos.net/microservices/smartcosmos-edge-relationships/index.html[API]|https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-ext-relationships.yml[smartcosmos-ext-relationships.yml]|
|Metadata|https://api.smartcosmos.net/microservices/smartcosmos-edge-metadata/index.html[API]|https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-edge-metadata.yml[smartcosmos-edge-metadata.yml]]|
|Bulk Import|https://api.smartcosmos.net/microservices/smartcosmos-edge-bulkimport/index.html[API]|https://github.çim/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-edge-bulkimport.yml[smartcosmos-edge-bulkimport.yml]|
Supports the mass import of datasets
|====================

Additional configuration files:

* Base configuration for all services: https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/application.yml[application.yml]
* Gateway https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-gateway.yml[smartcosmos-gateway.yml]
* Events https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-events.yml[smartcosmos-events.yml]
* Event listener https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/config/smartcosmos-event-listener.yml[smartcosmos-event-listener.yml]

== SMART COSMOS DevKit

The SMART COSMOS DevKit is a cluster of microservices, as the vital essence of our core platform and available to enable everybody that already has or maybe will have business with us. Thereby each Service is running in its own container. To manage these service containers we are using https://docker.com/[``docker``].

=== What is in the DevKit
With the DevKit it is possible to run a PaaS solution that supports a collection of best practices to engage any data processing relevant for your business.
Aside the composition of several standalone services you will get this:

* A full adaptable cloud-based PaaS
* A mircoservice architecture centric cluster
* The TRIM metapher - as best answer to handle IoT
* A server and databse agnostioc design (polyglot)
* A containerized operating environment (Docker)
* An extension based platform concept
* A future save and mdoern REST API
* A secured mircoservice communication (JWT)

=== Getting started
To jump right into operating the DevKit follow our https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit/blob/master/tutorials/getting-started.adoc[getting started tutorials].

== Next Steps

Depending on what aspect of the platform you need to extend, these services can act as starting points or samples:

 https://github.com/SMARTRACTECHNOLOGY/smartcosmos-event-listener[Event Listening]::
 This repository contains true sample code, that merely waits to see one of the many events on SMART COSMOS and gets called to output the event to the log.

 https://github.com/SMARTRACTECHNOLOGY/smartcosmos-edge-things[Complex Things]::
 SMART COSMOS Objects provides a "catch-all" things service that handles unknown things by default.  Ideally, you want to eventually optimize a particular thing, and this repository can provide a reference to either calling the generic thing service and the generic metadata service, or can merely be a guiding sample for how to implement the necessary REST API.

 https://github.com/SMARTRACTECHNOLOGY/smartcosmos-user-details-devkit[User Details]::
 In the Devkit user accounts are maintained inside a MariaDB database (the same database that holds the other data), in a production environment you would most likely want to use another database, or an external authentication provider like https://stormpath.com/[Stormpath], Active Directory, https://developers.google.com/identity/[Google], http://openid.net/[OpenID], etc.

== SMART COSMOS Objects License
You must review and accept the
https://licensing.smartcosmos.net/objects/[SMART COSMOS Objects EULA] before
working with this developer kit.
