= SMART COSMOS Getting Started Guide
SMARTRAC Technology Fletcher Inc <api@smartrac-group.com>

== Welcome to SMART COSMOS
Welcome to SMART COSMOS!

Are you ready to become part of creating something really big? With SMART COSMOS
you can connect a universe of everyday things to the digital world. In fact,
SMART COSMOS is the only platform that is purely focused on providing a fast
track for both enterprises and developers to Monetize the IoT.

SMART COSMOS is an ecosystem. It consists of a robust partner network where
hardware manufacturers, system integrators, software developers and enterprises
come together to create the IoT. It is comprised of both SaaS and PaaS offerings
that help you EMBED, ENABLE, and UTILIZE IoT driven data.

In order to accelerate value creation with the IoT, enterprises must learn how
to obtain new value from four key areas:

* Data
* Things
* People
* Process

The IoT is nothing more than combining a creative mixture of low-cost sensing
hardware, auto-identification technologies like RFID, and the Cloud! Now, we
invite you to take the next steps and learn how to use our IoT blueprint.

Platforms are living designs that are always evolving. If you have
feedback, feature requests, or just want to meet for some drinks and talk
software design patterns, contact us either at the developer portal or via
email: mailto:api@smartrac-group.com[api@smartrac-group.com]


== SMART COSMOS Objects License
You must review and accept the
https://licensing.smartcosmos.net/objects/[SMART COSMOS Objects EULA] before
working with this developer kit.

== Open Source Framework
SMART COSMOS includes a number of open sourced frameworks available under the
Apache License, Version 2. You can clone and freely use these frameworks in your
projects, submit pull requests, and access the latest documentation at GitHub:

 * https://github.com/SMARTRACTECHNOLOGY/smartcosmos-framework

 * https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit
(where this document was downloaded from)

IMPORTANT: The core of the Objects server itself is presently proprietary and must
be properly licensed when deployed in a production environment.

In addition to the open source development framework, the entirety of the
SMART COSMOS REST Web Service APIs are fully documented at our API web site,
https://documenter.getpostman.com/view/437937/smart-cosmos-objects-devkit-tutorial/2JvFAy (temporary location until we update our normal location -- https://api.smartcosmos.net)

== SMART COSMOS DevKit
The DevKit is a composition of several standalone services which are
communicating via REST. Each Services is running in its own container.
To manage these service containers we are using https://docker.com[`docker`].

IMPORTANT: You will need at least a basic understanding of docker for
confident and efficient usage of the DevKit.
If you are not familiar with docker you will find detailed
information in the
https://docs.docker.com/engine/understanding-docker/[official docker documentation].

To orchestrate the DevKit services
we are using `docker-compose`. If you seek for more details, e.g. about the
different command line options for `docker-compose`, consult the
https://docs.docker.com/compose/overview/[official docker-compose documentation].

=== Getting Started

To launch the SMART COSMOS DevKit follow our
link:tutorials/getting-started.adoc[getting started tutorial].
