= Tutorial for importing Sample Data

To get started with the SMART COSMOS Devkit, the database needs to be populated with initial data.

These types of data are required for minimal functionality:

* Tenant: A tenant represents an account or organization which holds all data belonging to it.
* User: An user owns credentials which are used to log on into the tenant. The first initial user is created together with the tenant.
* Things: Things represent physical objects (a car)
* Metadata: Metadata represent properties of these things (the car is blue)
* Relationships: Relationships represent relations between things (this car belongs to Bob)

== Create a Tenant

To create the new tenant, the *name* of the organization and the *username* of the initial user shall be given:

[source,bash]
----
curl -X POST -H "Content-Type: application/json" -d '{"name": "Example Company", "username": "waldo@example.com"}' "http://localhost:8080/tenants"
----

The response contains the URN of the new tenant, the first user with the Admin role and the initial password:

[source,json]
----
{
  "urn":"urn:tenant:uuid:ff002e1e-31c7-4153-a322-d024eb991748",
  "admin": {
    "urn":"urn:user:uuid:2e094c7c-52fe-4dbb-8954-2625171520f8",
    "username":"waldo@example.com",
    "password":"lajNVdjZtCEb",
    "roles":["Admin"],
    "tenantUrn":"urn:user:uuid:ff002e1e-31c7-4153-a322-d024eb991748"
  }
}
----

The password needs to be stored in a safe location, because it is required for further operations on this tenant and to create additional users.

== Acquire an Access Token

With the username and password known, the client requests an OAuth2 token, which is then used for all successive REST API calls.

[source,bash]
----
curl -X POST -H "Content-Type: application/json" --basic -u "smartcosmosservice:9HhnNDhfGEXfNEn6" "http://localhost:8080/oauth/token?grant_type=password&scope=read&username=waldo@example.com&password=lajNVdjZtCEb"
----

The response contains the OAuth2 token in *access_token*.

== Construct the bulk import request

The bulk import request is a JSON body composed from two sections:

* "things": a JSON array of things [T] with metadata [M]
* "relationships": a JSON array of relationships [R] between the things defined above

=== Example

We have a person and a car, where the person owns that car. The person and the car both have metadata properties:

[source,text]
----
[T] Person -> [M] {"name": "John"}
 |
 |
[R] "owns"
 |
 v
[T] Vehicle -> [M] {"manufacturer": "Toyota", "model": "pickup truck"}
----

To import this structure into the Devkit, an import JSON will be generated, which contains 2 things with metadata and
1 relationship. The thing's properties will be merged into the plain thing defined by type and urn to merge in the metadata:

[source,json]
----
{
  "things": [
    {
      "type":"Person",
      "urn":"urn:thing:uuid:12345678-1234-5678-9abc-000000000001",
      "name":"John"
    },
    {
      "type":"Vehicle",
      "urn":"urn:thing:uuid:12345678-1234-5678-9abc-000000000004",
      "manufacturer": "Toyota",
      "model": "Pickup Truck"
    }
  ],
  "relationships": [
    {
      "source": {
        "type":"Person",
        "urn":"urn:thing:uuid:12345678-1234-5678-9abc-000000000001"
      },
      "target": {
        "type":"Vehicle",
        "urn":"urn:thing:uuid:12345678-1234-5678-9abc-000000000004"
      },
      "relationshipType":"owns"
    }
  ]  
}
----

Store the final import data into a JSON file, then post it to the bulk import endpoint. Don't forget to set the correct JWT token, e.g.:

[source,bash]
----
token="eyJhbGci..." (it is quite long)

curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${token}" -d "$(cat bulkimport.json)" "http://localhost:8080/bulkimport/"
----

== Files in this Tutorial

* *BULKIMPORT.adoc* - this file
* *createSampleData* - bash script to create a new tenant and populate it with data
* *addSampleData* - bash script to log in into an existing tenant and add more data
* *createTenant.json* - example JSON which defines the new tenant
* *bulkimport.json* - example JSON which defines new Things, Metadata and Relationships to import

== Tips and Tricks

The script *createSampleData* outputs the username and password of the newly created tenant. Store these credentials in a safe location. When the import fails or more data needs to be imported, run following command with the given credentials:
[source,bash]
----
./addSampleData <username> <password>
----
So it is not neccessary to create a new tenant in the case the createSampleData command fails after creating the tenant.

For the bulk import the Thing urns need to be predefined. When the import fails, this might be caused by already existing urns in a different tenant.


