= Tutorial for importing Sample Data

To get started with the SMART COSMOS Devkit, the database needs to be populated with initial data.

These types of data are required for minimal functionality:

* Tenant: A tenant represents an account or organization which holds all data belonging to it.
* User: An user owns credentials which are used to log on into the tenant. The first initial user is created together with the tenant.
* Things: Things represent physical objects (a car)
* Metadata: Metadata represent properties of these things (the car is blue)
* Relationships: Relationships represent relations between things (ths car belongs to Bob)

== Create a Tenant

To create the new tenant, the *name* of the organization and the *username* of the initial user shall be given:

----
[source,bash]
----
curl -X POST -H "Content-Type: application/json" -d '{"name": "Example Company", "username": "waldo@example.com"}' "http://localhost:8080/tenants"
----

The response contains the URN of the new tenant, the first user with the Admin role and the initial password:

----
[source,json]
----
{
  "urn":"urn:tenant:uuid:ff002e1e-31c7-4153-a322-d024eb991748",
  "admin": {
    "urn":"urn:user:uuid:2e094c7c-52fe-4dbb-8954-2625171520f8",
    "username":"waldo@example.com",
    "password":"lajNVdjZtCEb",
    "roles":["Admin"],
    "tenantUrn":"urn:user:uuid:ff002e1e-31c7-4153-a322-d024eb991748"
  }
}
----

The password needs to be stored in a safe location, because it is required for further operations on this tenant and to create additional users.
