= Install the DevKit

Before you are able to start the DevKit make sure you have
link:prerequisites.adoc[installed all the prerequisites].

== Get the Deploy Code

 $ git clone https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit.git
 $ cd smartcosmos-devkit

[[startDevKit]]
== Start the DevKit

To enable you to access each service of the DevKit individually and not just
through the `gateway` service we forward all services to a specific
port.

CAUTION: Before you start the DevKit ensure that
no other application or service is listening on a
port listed in the column *Forwarded Ports* in the link:service-ports.adoc[List of Ports] table.

To start the DevKit we provide a script which will help you to get the DevKit
up and running. You may also use `docker-compose` directly
to start all the services.

To keep things simple we will use the start script. All you need to do is to
execute the following:

 $ ./start

== Next Steps

Now that you have a running DevKit you may follow
link:gettings-started.adoc[other getting started guides].
