:title: Sample Data Import Guide
:Author: SMART COSMOS Development Team
:Email: api@smartrac-group.com
:numbered:

= {title}

This guide helps you initially populate your database by importing
sample data into the SMART COSMOS DevKit, using the **Bulk Import**
service.

This data is required for minimum functionality:

.Data types
|===
| Type | Description

| Tenant | A tenant represents an account or organization which holds all data belonging to it
| User | A user is associated with credentials which are used to log in to a
          tenant. The initial user is created automatically when the tenant
          is created.
| Thing | Things represent core entities (a car, a person, an RFID tag, ...).
| Metadata | Metadata represents properties of these Things (the car is blue).
| Relationship | Relationships represent relations between Things (this car belongs to Bob)
|===

== Construct the Bulk Import Request

The bulk import request contains a JSON body composed of two sections:

.Bulk Import Components
|===
| Name | Description

| `things` | JSON array containing Things with Metadata
| `relationships` | JSON array containing Relationships between the
                    Things defined above
|===


=== Example

We have a person and a car, where the person owns that car. The person and the car both have metadata properties:

[source, text]
----
[Thing] Person -> [Metadata] {"name": "John"}
 |
 |
[Relationship] "owns"
 |
 v
[Thing] Vehicle -> [Metadata] {"manufacturer": "Toyota", "model": "pickup truck"}
----

To import this sample data structure, create a
JSON import file that looks like the JSON below,
and name it `bulkimport.json`.

[source, json]
----
{
  "things": [
    {
      "type": "Person",
      "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000001",
      "name": "John"
    },
    {
      "type": "Vehicle",
      "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000004",
      "manufacturer": "Toyota",
      "model": "Pickup Truck"
    }
  ],
  "relationships": [
    {
      "source": {
        "type": "Person",
        "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000001"
      },
      "target": {
        "type": "Vehicle",
        "urn": "urn:thing:uuid:12345678-1234-5678-9abc-000000000004"
      },
      "relationshipType": "owns"
    }
  ]
}
----

Use the `curl` command to import the data into the DevKit
(remember to set the correct access token):

[source, bash]
----
$ export token="eyJhbGci..."
$ curl -X POST "http://localhost:8080/bulkimport/" \
       -H "Content-Type: application/json" \
       -H "Authorization: Bearer ${token}" \
       -d @bulkimport.json
----

== Add more Sample Data

TODO:: rewrite this section

The script *createSampleData* outputs the username and
password of the newly created tenant. Store these credentials
in a safe location. When the import fails or more data
needs to be imported, run following command with the given
credentials:

 $ ./addSampleData USERNAME PASSWORD

So it is not necessary to create a new tenant in the case
the createSampleData command fails after creating the tenant.

For the bulk import the Thing urns need to be generated as
unique values. When the import fails, this might be caused
by already existing urns in a different tenant.

== Next Steps

To jump right into operating the DevKit, follow our
link:../README.adoc[getting started guides].
