# server:
# Debug option: prevent timeout
#  session:
#    timeout: 60000

management:
  port: 8081
  # security:
  #   enabled: false

eureka:
  client:
    enabled: false

smartcosmos:
  service:
    kafka:
      host: ${KAFKA_HOST:'http://kafka'}
      port: 9092
      address: ${smartcosmos.service.kafka.host}:${smartcosmos.service.kafka.port}
    zookeeper:
      host: ${ZOOKEEPER_HOST:'http://zookeeper'}
      port: 2181
      address: ${smartcosmos.service.zookeeper.host}:${smartcosmos.service.zookeeper.port}
    gateway:
      host: ${GATEWAY_HOST:'http://gateway'}
      port: 8080
      address: ${smartcosmos.service.gateway.host}:${smartcosmos.service.gateway.port}
    auth-server:
      host: http://auth-server
      port: 8080
      address: ${smartcosmos.service.auth-server.host}:${smartcosmos.service.auth-server.port}
    config-server:
      host: http://config-server
      port: 8080
      address: ${smartcosmos.service.config-server.host}:${smartcosmos.service.config-server.port}
    edge-things:
      host: http://edge-things
      port: 8080
      address: ${smartcosmos.service.edge-things.host}:${smartcosmos.service.edge-things.port}
    edge-user:
      host: http://edge-user
      port: 8080
      address: ${smartcosmos.service.edge-user.host}:${smartcosmos.service.edge-user.port}
    events:
      host: http://events
      port: 8080
      address: ${smartcosmos.service.events.host}:${smartcosmos.service.events.port}
    ext-metadata:
      host: http://ext-metadata
      port: 8080
      address: ${smartcosmos.service.ext-metadata.host}:${smartcosmos.service.ext-metadata.port}
    ext-things:
      host: http://ext-things
      port: 8080
      address: ${smartcosmos.service.ext-things.host}:${smartcosmos.service.ext-things.port}
    ext-relationships:
      host: http://ext-relationships
      port: 8080
      address: ${smartcosmos.service.ext-relationships.host}:${smartcosmos.service.ext-relationships.port}
    user-details:
      host: http://user-details
      port: 8080
      address: ${smartcosmos.service.user-details.host}:${smartcosmos.service.user-details.port}

  datasource:
    default-host: mysql
    default-username: cosmos
    default-password: dev
    default-db: devkit

info:
  description: SMART COSMOS Cluster Services
  url: https://www.smart-cosmos.com/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000


security:
  oauth2:
    client:
      accessTokenUri: ${smartcosmos.authorization-server}/oauth/token
      user-authorization-uri: ${smartcosmos.authorization-server}/oauth/authorize
      client-id: 'smartcosmosservice'
      client-secret: '9HhnNDhfGEXfNEn6'
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhLD+JUbjIKXzIJECP19V
          EKW5MQCFM7sIRiHeEgSh9pSpcn0W2fyDgUfZuSgWp6GCjmRaTrFwVt9zhUrOC/Nq
          VyaYvV5nwqaNv02CkAMpRBWpFKcdMdx2mMjDGvklY2BIvG8X/9BWUhWyvX5Ye0Vb
          MLIfcg2sLcqJQ/tpB9GAZJGitjP051KEJuOodrZTUQwrcz7cIUQGsT3jau5WjyIm
          wc7WG5jExUkXMcdRIo9eQAMNfl/PpW1eb648Tymmj4C4pT5DTYIjF0p6V+TSCfaP
          H7qQPYIAx4HfKd74sY/0Jom42Vml4YnNZuDQWm9Z+K79MI3GQXbXB/Rng+fAwilf
          PQIDAQAB
          -----END PUBLIC KEY-----

spring:
  jackson:
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true

logging:
  level:
    ROOT: INFO
    com.netflix:
      eureka.registry: WARN
      discovery.shared.resolver.aws.ConfigClusterResolver: WARN
    org.apache.kafka.clients:
      producer: WARN
      consumer: WARN
