# User Details DevKit configuration

server:
  port: ${smartcosmos.service.user-details.port}

flyway:
  enabled: true
  baselineOnMigrate: true
  
spring:
  datasource:
    #
    # DROP DATABASE devkit; CREATE DATABASE devkit;  GRANT ALL PRIVILEGES ON devkit.* TO 'cosmos'@'localhost' IDENTIFIED BY 'dev';  FLUSH PRIVILEGES;
    #
    url: jdbc:mysql://${smartcosmos.datasource.default-host}/${smartcosmos.datasource.default-db}
    username: ${smartcosmos.datasource.default-username}
    password: ${smartcosmos.datasource.default-password}
    driver-class-name: org.mariadb.jdbc.Driver
    ## XXX Note that in the migration to Spring Boot 1.4 these will need to move:
    test-on-borrow: true
    validation-query: SELECT 1
    ## Uncomment for Spring Boot 1.4
    # tomcat:
    #   test-on-borrow: true
    #   validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

smartcosmos:
  security:
    enabled: true
    resource:
      user-details:
        user:
          name: '{cipher}05b479a618112ef05d1e99c1b9f203405ba6d24e0ef12b76764c8af11da679f1'
          password: '{cipher}95aa290e4fd9d380ef9fe9abb492065d1fff2b74f4c32a3aa8c8c07a7882b997'
