info:
  component: Auth Server

server:
  port: ${smartcosmos.service.auth-server.port}

security:
  oauth2:
    client:
      accessTokenUri:
      user-authorization-uri:
      client-id:
      client-secret:

logging:
  level:
    ROOT: INFO
    org.springframework:
        security: INFO
        web.client: INFO

smartcosmos:
  security:
    resource:
      keystore:
        location: "classpath:smartcosmos.jks"
        password: '{cipher}cbe4de5a96b0fcb880d8a98e735ea02393cde3a519a5b4424d1cfc7f2ba5c2df'
        keypair: smartcosmosdev
        keypairPassword: '{cipher}00bc63a48db23ec844932c74b5a0afa9e8cecff87f932cac1a462299d46478c5'
      client-id: '{cipher}ef4e264a69ea97cf574bc96b7bcf364af4a9ab61fb2ad17097e88311d2878eb42e265b0a05e46c3f1ed9172ee1e335fd'
      client-secret: '{cipher}af7a1662ba0d19daf3f5e3ab2da8947f243ba3bc14d889d21627223bbed726f8e7ac793a8952c00367343918134daef8'
      user-details:
        user:
          name: '{cipher}05b479a618112ef05d1e99c1b9f203405ba6d24e0ef12b76764c8af11da679f1'
          password: '{cipher}95aa290e4fd9d380ef9fe9abb492065d1fff2b74f4c32a3aa8c8c07a7882b997'
        server:
          location-uri: ${smartcosmos.service.user-details.address}
      cachedUserKeepAliveSecs: 300
