server:
  port: ${smartcosmos.service.ext-interactions.port}

smartcosmos:
  security:
    enabled: true
  endpoints:
    interactions:
      enabled: true
      create.enabled: true
  interactions:
    kafka:
      host: ${smartcosmos.service.kafka.address}
      port: 9092
      address: ${smartcosmos.service.kafka.host}:${smartcosmos.service.kafka.port}

