:title: Getting Started
:Author: SMART COSMOS Development Team
:Email: api@smartrac-group.com
:numbered:
:linkattrs:

= Getting Started

Getting Started provides you with an overview of basics steps to familiarize you
with the SMART COSMOS DevKit.

The guide informs you about recommended system requirements and guides you through the
process of setting up the SMART COSMOS DevKit and how to proceed from there.

== Prerequisites

Please choose the matching platform of your working machine:

* link:prerequisites.adoc#macOS[macOS]
* link:prerequisites.adoc#linux[GNU/Linux]

== Set up the DevKit

To start the DevKit follow the
link:install-devkit.adoc[DevKit Setup Guide].


[guides]
== Guides

link:devkit-basics.adoc[DevKit Basics]::
This guide helps you get started with the SMART COSMOS DevKit. We'll
describe the pieces of the DevKit and show you how to use the APIs with working
examples.

== Next Steps
Now that you have an understanding on how to operate and use
the DevKit you may follow link:../README.adoc#nextSteps[the next steps].
