:title: SMART COSMOS DevKit Troubleshooting
:Author: SMART COSMOS Development Team
:Email: api@smartrac-group.com
:imagesdir: images

= {title}

This document describes the most common problems and causes encountered when
working with the SMART COSMOS DevKit.  If you have encountered a problem not
described here and you are not able to resolve it on your own
 please contact us at {email}.

[qanda]
Requests fail with `Failed to connect to localhost port 8080: Connection refused`::
  The most common cause of this problem is the Gateway not running or the
  gateway is not running on port 8080.  Run the command `docker ps` and verify
  an instance of the `smartcosmos/gateway` is running on port 8080.  The
  information should look similar to the following:

  CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                     NAMES
  9fb926fddbd6        smartcosmos/gateway         "./entrypoint.sh /opt"   5 hours ago         Up 43 minutes       0.0.0.0:8080->8080/tcp    smartcosmosdevkit_gateway_1

Every time the Docker engine is started some of the DevKit containers attempt to start automatically.::
 This is most likely because you did not run `docker-compose down` to stop and delete the DevKit containers,
 and there are containers using the restart policy _always_. By default, this parameter is used by `user-details-devkit`,
 as you can see in `docker-compose.yml`. Make sure to use `docker rm` to remove all instances of these services,
 or use `docker rm $(docker ps -aq)` to remove all existing containers at once. *Be careful, this may also delete
 containers you might want to keep!*
